baseDir: /gerby-data

collection: fingerPieces

gerby:
  collections:
    fingerPieces:
      plastexDir: $baseDir
      webserver:
        host: '0.0.0.0'
        #host: '127.0.0.1'
        port: 5000
    diSimplex:
      plastexDir: $baseDir
      webserver:
        host: '0.0.0.0'
        #host: '127.0.0.1'
        port: 5000
