#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the gerbyRun command anywhere in a user's
# workspace.

##########################################################################

installCmd() {
cmdName=$1

recordcmdScript=$(pwd)/.venv/bin/$cmdName

cat << CMD_SCRIPT > $HOME/.local/bin/$cmdName
#!/bin/sh

# This shell script was created by the pygments-tools tool
#       './scripts/installEditableGerbyRunnerCommands'
# script.

exec $recordcmdScript \$@
CMD_SCRIPT

chmod a+x $HOME/.local/bin/$cmdName
}

##########################################################################

#installCmd gerbyInit
installCmd gerbyRun

echo ""
echo "Editable gerbyRun commands have been created"
echo ""
